in:
  type: file
  path_prefix: /home/koreantramp/./csv_files/customer
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: user_id, type: string}
    - {name: first_name, type: string}
    - {name: last_name, type: string}
    - {name: job_title, type: string}
out:
  type: postgresql
  host: localhost
  port: 5432
  user: postgres
  password: 12345
  database: td_coding_challenge
  table: customers_tmp
  mode: insert

[root@localhost try1]# cat config_pageview_data_load.yml
in:
  type: file
  path_prefix: /home/koreantramp/./csv_files/pageview
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: user_id, type: string}
    - {name: url, type: string}
    - {name: user_agent, type: string}
    - {name: timestamp, type: string}
out:
  type: postgresql
  host: localhost
  port: 5432
  user: postgres
  password: 12345
  database: td_coding_challenge
  table: pageviews_tmp
  mode: insert

